apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: response-route
metadata:
  annotations:
    description: A group of interconnected demo services for testing Open Shift Service Mesh.
    iconClass: icon-openshift
  labels:
    template: response-route
  name: response-route
objects:

##################################################################################################
# Route
##################################################################################################

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${RESPONSE_ROUTE_NAME}
  spec:
    host: ${RESPONSE_ROUTE}
    to:
      kind: Service
      name: istio-ingressgateway
      weight: 100
    port:
      targetPort: http2
    tls:
      termination: edge

###############################################################################
# Parameters
###############################################################################

parameters:

- description: Route URL for external access to response service
  name: RESPONSE_ROUTE
  displayName: Route URL for external access to response service
  required: true
- description: Name of the route for external access to response service
  name: RESPONSE_ROUTE_NAME
  displayName: Name of the route for external access to response service
  required: true
